### ISSUE TITLE
Using response classes that contain Object type

### ISSUE THREAD

**Issue by urifridland** [outbrain/ob1k#47]
When I'm adding an action which response is a class that contains an Object type, for example:

```
public ComposableFuture<MyClass> GetMyClass(){
   ...
}
```

where:

```
public class MyClass {
    private Object a;

    public Object getA(){
        return a;
    }
}
```

I get the following exception upon service start:
(I would expect it to resolve the type from the value)

```
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  java.lang.Object _$$_t;
  if ($2 == null) {
    _$$_t = new java.lang.Object();
  } else {
    _$$_t = (java.lang.Object) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}


org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  java.lang.Object _$$_t;
  if ($2 == null) {
    _$$_t = new java.lang.Object();
  } else {
    _$$_t = (java.lang.Object) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}


    at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:575)
    at org.msgpack.template.TemplateRegistry.register(TemplateRegistry.java:158)
    at org.msgpack.MessagePack.register(MessagePack.java:602)
    at com.outbrain.ob1k.common.marshalling.MessagePackRequestMarshaller.registerBean(MessagePackRequestMarshaller.java:291)
    at com.outbrain.ob1k.common.marshalling.MessagePackRequestMarshaller.registerTypes(MessagePackRequestMarshaller.java:90)
    at com.outbrain.ob1k.common.marshalling.MessagePackRequestMarshaller.registerBean(MessagePackRequestMarshaller.java:287)
    at com.outbrain.ob1k.common.marshalling.MessagePackRequestMarshaller.registerTypes(MessagePackRequestMarshaller.java:90)
    at com.outbrain.ob1k.common.marshalling.MessagePackRequestMarshaller.registerTypes(MessagePackRequestMarshaller.java:69)
    at com.outbrain.ob1k.common.marshalling.RequestMarshallerRegistry.registerTypes(RequestMarshallerRegistry.java:34)
    at com.outbrain.ob1k.server.registry.ServiceRegistry.register(ServiceRegistry.java:138)
    at com.outbrain.ob1k.server.registry.ServiceRegistry.register(ServiceRegistry.java:262)
    at com.outbrain.ob1k.server.build.ServerBuilder.registerServices(ServerBuilder.java:386)
    at com.outbrain.ob1k.server.build.ServerBuilder.build(ServerBuilder.java:402)
    at com.windward.temporalproperties.TemporalPropertiesServiceServer.buildServer(TemporalPropertiesServiceServer.java:40)
    at com.windward.temporalproperties.TemporalPropertiesServiceServerTest.buildServer(TemporalPropertiesServiceServerTest.java:13)
    at com.windward.web.util.AbstractServerTestBase.setup(AbstractServerTestBase.java:23)
    at com.windward.temporalproperties.TemporalPropertiesServiceServerTest.setUp(TemporalPropertiesServiceServerTest.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  java.lang.Object _$$_t;
  if ($2 == null) {
    _$$_t = new java.lang.Object();
  } else {
    _$$_t = (java.lang.Object) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}

    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
    at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
    at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:119)
    at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
    at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
    ... 43 more
Caused by: javassist.CannotCompileException: by java.lang.SecurityException: Prohibited package name: java.lang
    at javassist.ClassPool.toClass(ClassPool.java:1099)
    at javassist.CtClass.toClass(CtClass.java:1265)
    at org.msgpack.template.builder.BuildContext.createClass(BuildContext.java:154)
    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
    ... 47 more
Caused by: java.lang.SecurityException: Prohibited package name: java.lang
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:659)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at javassist.ClassPool.toClass2(ClassPool.java:1112)
    at javassist.ClassPool.toClass(ClassPool.java:1093)
    ... 50 more

```

**Comment by eranharel** [comment]
MessagePack 0.6.x doesn't support serializing Object instances out of the box.
You need to refer to the MessagePack documentation to resolve this (there are examples there).
